import fs from 'fs';
import { exec } from 'child_process';
import { promisify } from 'util';
import { NtpConfig, NtpStatus } from '../types/ntp';

const execAsync = promisify(exec);

export class NtpService {
  private configPath = process.env.NTP_CONFIG_FILE || '/etc/chrony/chrony.conf';

  async getConfig(): Promise<NtpConfig> {
    if (!fs.existsSync(this.configPath)) {
      return { enabled: false, servers: [], allowSubnets: [] };
    }

    const content = fs.readFileSync(this.configPath, 'utf8');
    const servers: string[] = [];
    const subnets: string[] = [];

    const lines = content.split('\n');
    for (const line of lines) {
      if (line.startsWith('pool ') || line.startsWith('server ')) {
        const parts = line.split(' ');
        if (parts.length > 1) servers.push(parts[1]);
      } else if (line.startsWith('allow ')) {
        const parts = line.split(' ');
        if (parts.length > 1) subnets.push(parts[1]);
      }
    }

    // Check if the chronyd process is running to determine "enabled"
    const isEnabled = await this.isRunning();

    return {
      enabled: isEnabled,
      servers,
      allowSubnets: subnets
    };
  }

  async updateConfig(config: NtpConfig): Promise<void> {
    let content = "# Generated by DNSmasq GUI\n";
    content += "driftfile /var/lib/chrony/drift\n";
    content += "makestep 1.0 3\n";
    content += "rtcsync\n\n";

    for (const server of config.servers) {
      content += `pool ${server} iburst\n`;
    }

    content += "\n";
    for (const subnet of config.allowSubnets) {
      content += `allow ${subnet}\n`;
    }

    fs.writeFileSync(this.configPath, content);

    if (config.enabled) {
      await this.restart();
    } else {
      await this.stop();
    }
  }

  async getStatus(): Promise<NtpStatus> {
    const running = await this.isRunning();
    let synchronized = false;
    let source = undefined;

    if (running) {
      try {
        // -n for numeric, -c for csv-ish, or just check the tracking
        const { stdout } = await execAsync('chronyc tracking');
        // 'Leap status' is 'Normal' when synced
        synchronized = stdout.includes('Leap status     : Normal');

        // Extract source from tracking output if possible (to avoid truncation)
        // Format: Reference ID    : CB100801 (lithium.constant.com)
        const refIdLine = stdout.split('\n').find(l => l.startsWith('Reference ID'));
        const match = refIdLine?.match(/\(([^)]+)\)/);
        if (match && match[1]) {
          source = match[1];
        }

        // Fallback or double-check with sources if tracking didn't give a clear name
        if (!source || source === 'LOCAL') {
          const sourceRes = await execAsync('chronyc -N sources');
          const lines = sourceRes.stdout.split('\n');
          const syncLine = lines.find(l => l.startsWith('^*'));
          if (syncLine) {
            source = syncLine.split(/\s+/)[1];
          }
        }
      } catch (err) {
        // May fail if chronyc is not ready
      }
    }

    return {
      active: running,
      synchronized,
      source
    };
  }

  private async isRunning(): Promise<boolean> {
    try {
      await execAsync('pgrep chronyd');
      return true;
    } catch {
      return false;
    }
  }

  private async restart(): Promise<void> {
    try {
      if (await this.isRunning()) {
        await execAsync('pkill chronyd');
        // Give it a second to release the socket
        await new Promise(resolve => setTimeout(resolve, 500));
      }
      await execAsync('chronyd');
    } catch (err) {
      console.error('Failed to restart chrony:', err);
    }
  }

  private async stop(): Promise<void> {
    try {
      await execAsync('pkill chronyd');
    } catch (err) {
      // Ignore if not running
    }
  }
}
