# DNSmasq advanced configuration managed by dnsmasq-gui
# This section contains general DNS and DHCP settings

domain=voicelab.xyz
address=/voicelab.xyz/192.168.10.94
cache-size=150
neg-ttl=3600
local-ttl=60
no-resolv
no-hosts
server=8.8.8.8
server=8.8.4.4
log-queries
log-dhcp

# Include managed configuration files
conf-file=/etc/dnsmasq.d/dnsmasq-static-leases.conf
conf-file=/etc/dnsmasq.d/dnsmasq-ranges.conf
conf-file=/etc/dnsmasq.d/dnsmasq-options.conf
